/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  260: {},
  37111: {},
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
